language: php
sudo: required
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
before_install:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update -q
  - sudo apt-get install libsodium-dev -y
  - pecl install libsodium
before_script:
  - composer install

script: phpunit --coverage-text tests
